function cfg = CESTA1987_config()
% Central configuration for the CESTA 1987 QES-Dense analysis suite.
%
% Put this file and the other .m files in:
% I:\LMZ\QES\LMZ_QES_CESTA1987\MATLAB分析
%
% The project and Output folders are resolved relative to this file.

cfg.matlabDir  = fileparts(mfilename('fullpath'));
cfg.projectDir = fileparts(cfg.matlabDir);
cfg.outputDir  = fullfile(cfg.projectDir,'Output');
cfg.resultsDir = fullfile(cfg.matlabDir,'Results');
if ~exist(cfg.resultsDir,'dir'), mkdir(cfg.resultsDir); end

% Main outputs generated by the supplied QES input/run scripts.
cfg.observationCsv = fullfile(cfg.outputDir,'observation_sampler.csv');
cfg.aerosolSamplerCsv = fullfile(cfg.outputDir,'aerosol_sampler.csv');
cfg.componentCsv   = fullfile(cfg.outputDir,'component_history.csv');
cfg.parcelCsv      = fullfile(cfg.outputDir,'parcel_mass_diagnostic.csv');
cfg.windsVizNc     = fullfile(cfg.outputDir,'lmz_windsOut.nc');
cfg.windsWkNc      = fullfile(cfg.outputDir,'lmz_windsWk.nc');
cfg.turbNc         = fullfile(cfg.outputDir,'lmz_turbOut.nc');
cfg.plumeNc        = fullfile(cfg.outputDir,'lmz_plumeOut.nc');

% Experimental/source setup from CESTA1987plume.xml / CESTA report.
cfg.sourceXYZ = [550.0 100.0 3.15];
cfg.sourceMass_kg = 146.2;
cfg.releaseStart_s = 2.0;
cfg.releaseEnd_s   = 1807.0;
cfg.releaseDuration_s = 1805.0;
cfg.releaseRate_g_s = 80.9;
cfg.exitVelocity_m_s = 3.66;
cfg.exitTemperature_C = 107.4;

% Ambient setup.
cfg.temperature_K = 286.15;
cfg.relativeHumidity = 0.722;
cfg.pressure_Pa = 101300;
cfg.airDensity_kg_m3 = 1.228294;
cfg.stabilityClass = 'C';

% Direct-entry vertical mean profile used by sensor1/2/3.xml.
cfg.windZ_m = [2 10 18 28]';
cfg.windSpeed_m_s = [2.8 3.3 3.6 3.8]';
cfg.windFrom_deg = 122.7;       % QES sensor convention: wind FROM
cfg.plumeAzimuth_deg = 302.7;   % CESTA downwind/plume-path azimuth

% Model grid.
cfg.domain_m = [700 700 50];
cfg.cell_m = [1 1 0.5];

% D3/Hanna-style model-performance thresholds used in prior QES work.
cfg.metricTol = 1e-12;
end
